### ISSUE TITLE
Traduction d'articles intéressants en anglais

### ISSUE THREAD

**Issue by kud** [putaindecode/organisation#27]
Hello,

Je me disais qu'il serait pas mal parfois de faire des traductions d'articles de l'anglais vers le français. On ferait certes de l'ombre à pompage mais comme il existe souvent des articles anglais bien pertinents et qu'écrire un article prend du temps, pourquoi ne pas parfois traduire des articles d'anglais à français.

**Comment by MoOx** [comment]
On va faire nos propres trad en anglais, j'ouvre un autre sujet. Le contenu de p! doit imo rester exclusif.
