### ISSUE TITLE
Request: t-shirts, stickers

### ISSUE THREAD

**Issue by kud** [putaindecode/organisation#30]
Etant donné qu'on est fiers de notre crew et qu'on va de plus en plus sponsoriser des évènements, des projets, etc, ce serait cool qu'on ait des stickers et/ou des t-shirts p!, qu'en dites-vous ?

**Comment by magsout** [comment]
up

**Comment by magsout** [comment]
La version de @lionelB est cool

**Comment by MoOx** [comment]
Je trouve qu'on voit pas assez le P!.
Faudrait faire d'autre essais.

**Comment by bloodyowl** [comment]
on les fait quand ces putain de tees?

—
mlb

**Comment by lionelB** [comment]
on pourrait p-e inverser les couleurs  (je regarde si j'ai encore le modèle)

**Comment by magsout** [comment]
>on pourrait p-e inverser les couleurs (je regarde si j'ai encore le modèle)


Effectivement. peut-être comme ça

**Comment by MoOx** [comment]
Bon je vois ça https://twitter.com/art_developpeur/status/601001806240587776

> on les fait quand ces putain de tees?

Clair. Je veux un tshirt p!, sur une boutique. Genre là.

J'aime bien les cols en V, vous aimez ou pas ?

On pourrait aussi offrir blanc et logo classic + rouge et logo inversé ?

**Comment by MoOx** [comment]
![screen shot 2015-05-22 at 23 17 18](https://cloud.githubusercontent.com/assets/157534/7779876/cb409e68-00d8-11e5-86ff-a66a09f1cde0.png)

**Comment by MoOx** [comment]
![screen shot 2015-05-22 at 23 22 50](https://cloud.githubusercontent.com/assets/157534/7779936/7fab0096-00d9-11e5-8853-c7b14b9ec9d7.png)


http://www.spreadshirt.com/-C59/product/1006153675/view/1/sb/l

**Comment by kud** [comment]
J'aime bien le premier je crois. :)

**Comment by MoOx** [comment]
![screen shot 2015-05-22 at 23 25 00](https://cloud.githubusercontent.com/assets/157534/7779969/cc739ba4-00d9-11e5-8636-7f07e2b546ac.png)

http://www.spreadshirt.com/-C59/product/1006153732/view/1/sb/l

**Comment by MoOx** [comment]
![screen shot 2015-05-22 at 23 27 12](https://cloud.githubusercontent.com/assets/157534/7780014/201a62ec-00da-11e5-8fe0-eedc25655d23.png)

J'arrête de mettre le lien car je vois que ce con met met toujours le même.

**Comment by MoOx** [comment]
Je suis assez fan de la dernière version. Peu de choix sur la typo.
On pourrait même faire une boutique spreadshirt ça serait fun :D

**Comment by kud** [comment]
J'aime pas avec l'url ou au pire, dans le dos.

**Comment by MoOx** [comment]
Bah sans rien devant, tu communiques pas sur la communauté je trouve. Sinon avec "Putain de code !"

**Comment by MoOx** [comment]
![screen shot 2015-05-22 at 23 34 21](https://cloud.githubusercontent.com/assets/157534/7780103/2a5d64ce-00db-11e5-9ada-a8cf30d2a030.png)

**Comment by kud** [comment]
Ma remarque était purement graphique. Et dans le dos ça te plait pas ?

**Comment by MoOx** [comment]
Je trouve que ca manque a être vu :/
Mais on pourrait mettre le titre d'un côté et l'url de l'autre.

**Comment by kud** [comment]
Si tu veux mettre absolument le lien alors : https://cloud.githubusercontent.com/assets/157534/7780014/201a62ec-00da-11e5-8fe0-eedc25655d23.png

**Comment by magsout** [comment]
Je suis assez d'accord avec @kud . Le premier est top. L'URL même si ça apporte de l'information graphiquement ca casse un peu le logo.

Le 1er je kiffff

**Comment by MoOx** [comment]
Et le dernier avec "Putain de code !" en light en petit ?

Voir ça  la limite

![screen shot 2015-05-23 at 05 36 20](https://cloud.githubusercontent.com/assets/157534/7782274/bc06dcca-010d-11e5-8d39-32698e522f1f.png)

**Comment by Nyalab** [comment]
celui avec le logo + l'url est top : https://github.com/putaindecode/organisation/issues/30#issuecomment-104778796

ça apporte l'info du logo le plus light visuellement + l'url (les gens ne vont pas reconnaitre notre logo comme on reconnait celui de google ou apple, on est pas des rock stars)

j'y verrais même un petit pseudo personnalisé derrière, c'est possible ?

**Comment by MoOx** [comment]
Oui c'est possible pour le pseudo, ça rajoute encore 4$ cela dit

Petit test avec l'url en plus light

![screen shot 2015-05-28 at 09 22 33](https://cloud.githubusercontent.com/assets/157534/7854578/208d9088-051b-11e5-861b-d55dfa6698f3.png)

Exemple avec le nom derrière

![screen shot 2015-05-28 at 09 23 25](https://cloud.githubusercontent.com/assets/157534/7854585/399e4cac-051b-11e5-810b-f85dc8ad2299.png)

Vu comment les gens se pressent pas, le plus simple et que chacun se prenne le sien. Voilà vous avez le lien vers le tshirt en cours http://www.spreadshirt.com/-C59/product/1006153732/view/1/sb/l
vous pouvez l'ajuster selon vos besoin.

_Juste avant qu'on se tape des barres, je voudrais savoir si oui on non on bouge sur le .io (qu'on ai à peut prêt tous le même tshirt)? Si ça vous va, je fais la migration du nom de domaine, puis à ce moment là, perso je me prends ce t-shirt._

Si vous êtes ok, je vais essayer de faire une boutique spreadshirt pour qu'on foute le lien sur notre site, ça sera bien fun ^^

Merci de prendre 2min pour donner votre avis :)

**Comment by kud** [comment]
+1 pour ce template

Compliqué pour le .fr/.io. A la fois je suis d'accord avec les traductions, à la fois l'objectif c'était tout de même d'être franco-français. Des sites anglais qui sont bons, il y en a pas mal.

**Comment by Macxim** [comment]
:+1: 
Pour ma part, OK pour le .io.
Il est cool ce dernier modèle oui.
Est-ce que c'est le bon lien @MoOx ? Sur celui que tu as donné, c'est encore celui avec la bulle.

**Comment by MoOx** [comment]
http://www.spreadshirt.com/-C59/product/1006225196/view/2/sb/l

**Comment by MoOx** [comment]
pardon http://www.spreadshirt.com/-C59/product/1006225196/view/1/sb/l

(note sur firefox ca marche pas bien on dirait, je passe par safari)

**Comment by Macxim** [comment]
Top, j'achète direct (quand tout le monde est OK).

**Comment by MoOx** [comment]
réglons l'histoire du domaine avant :)

**Comment by Nyalab** [comment]
il est parfait, go avec le .io, le tee shirt est nickel avec le nick et tout

**Comment by MoOx** [comment]
Pour info, je compte faire la migration vers le .io avant mi novembre et avoir acheter le t-shirt que j'ai posé avant d'ici là afin de le porter à la conf codeurenseine :)

Rappel: ![screen shot 2015-05-28 at 09 22 33](https://cloud.githubusercontent.com/assets/157534/7854578/208d9088-051b-11e5-861b-d55dfa6698f3.png)
Rappel 2 ça marche pas sur firefox (il manque les images, le plus important quoi)
http://www.spreadshirt.com/-C59/product/1006225196/view/1/sb/l

**Comment by MoOx** [comment]
Je viens de m'en prendre un. Je pense que si ça rend bien, je ferais une page "shop" sur le site avec des mugs et ce genre de connerie.

**Comment by MoOx** [comment]
Closing in favor of https://github.com/putaindecode/putaindecode.fr/issues/492
