### ISSUE TITLE
License sur les articles ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#32]
Je lisais un truc complètement ailleurs et je suis tombé ici

http://sametmax.com/appel-a-contributeurs-impertinents/

ou il parle de license creative common pour les articles.

On s'est déjà posé la question ?

**Comment by MoOx** [comment]
up.
CC ou on garde un copyright ?

**Comment by kud** [comment]
J'ai jamais su quoi mettre en licence. CC me parait pas mal.

**Comment by magsout** [comment]
J'y connais rien en licence. Juste qu'on me demande pour utiliser mon article, après on en fait ce qu'on en veut.

Ca donne quoi ça comme licence ?

**Comment by Nyalab** [comment]
http://choosealicense.com/

**Comment by magsout** [comment]
CC BY me semble bien alors

**Comment by MoOx** [comment]
Intéressant comme point de vue. https://css-tricks.com/license/
Mais bon sur le papier c'est pas une license, donc à voir. La CC By me semble juste.

Je partierais sur la CC by (source) nc (non commercial) sa (forks doivent être sous cette même license)

https://creativecommons.org/licenses/by-nc-sa/4.0/

Vous en dites quoi ?

**Comment by lionelB** [comment]
:+1:  CC by (source) 
pour le NC ou pas... je crois que je m'en fou

**Comment by Nyalab** [comment]
nickel @moox
