### ISSUE TITLE
Mise en avant (ou pas) des posts

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#34]
Hello la team.

Ma question est simple: comment on gère les posts qu'on pense que dans le fond "bof" ?

Genre le post sur ember est bien sur la forme, mais bon ici on aime pas trop (si je me trompe pas) les frameworks en général, donc on va pas etre tendance à dire aux gens de les utiliser donc est-ce qu'on devrait pas mettre des signes genre "attention ce post n'est pas vraiment le reflet de l'équipe éditorial", non ?

On met des flags sur les auteurs ? Ou les posts ?

Vous en pensez quoi ?

**Comment by MoOx** [comment]
je vais tenter de rajouter une étoile sur les posts, je ferme ici et ouvre sur le site.

**Comment by kud** [comment]
Oui okay pour ça.
