### ISSUE TITLE
Url: faudrait qu'on fasse un arbre bien logique que ça bouge plus

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#35]
Pour éviter les déplacements de posts & co, faudra une arbo simple, générique et efficace.
Je pense que vu qu'on a un peu  de contenu ca peut etre le moment de faire un point

Voilà l'état des lieux:

![](https://cloudup.com/csALOyrVniU+)

Et voilà mes premières remarques:

- c'est pas mal les dossier par langages
- faudrait exploser `backend` en `ruby` et `go`.
- dans la même idée `frontend` on devrait l'exploser, mais en même temps je vois pas trop ou ranger ces posts vu qu'ils font intervenir plusieurs langages.
- je regrouperais bien les dossiers `hack`, `sublime-text` et `windows` dans un même type genre `workflow` ou `setup` ou un truc dans le genre `env`.

Pour mon dernier point, ça rejoint un peu `env` (genre le post sur windows irait nikel dans ce dossier je trouve). Peut être qu'on le renomme en truc plus générique et qui fait moins penser à "variable d'env" ?

Je rajoute un point en suspens: est-ce qu'on garde un arbo à plat ou est-ce qu'on fait des sous dossier ? genre `frontend/{css|js}`...

Que pensez-vous de tout ça ?

**Comment by MoOx** [comment]
Relance avant que je prenne une décision a la kim jong un

**Comment by kud** [comment]
Faut effectivment que je vérifie cela, j'ai trouvé que c'était le bordel côté dossier quand j'ai rajouté mon post.

**Comment by MoOx** [comment]
CA SERAIT BIEN QU'ON VOIT CA A PLUSIEURS NAN ?

**Comment by MoOx** [comment]
Sinon j'vais faire mon nazi est imposé un arbre :)

**Comment by kud** [comment]
Les nazis n'aimaient pas les arbres, ils rasaient tout.

**Comment by kud** [comment]
(mais dans l'idée, faudrait en discuter oui).

**Comment by MoOx** [comment]
Ce thread est là pour ça. J'ai posé assez de billes pour attendre des retours :)

**Comment by kud** [comment]
Je pense qu'il faut qu'on ait forcément un dossier par techno déjà. (css, js, etc).

**Comment by MoOx** [comment]
@bloodyowl a jeté l'idée de tout mettre à plat mais ça met à mal mon idée pour https://github.com/putaindecode/putaindecode.fr/issues/344

**Comment by MoOx** [comment]
J'ai réfléchit un peu (ça m'arrive)
Que penses vous de:
- mettre à plat, avec des dates devant les posts genre content/posts/fr/2015-02-32-url-du-post puis au build on supprime cette date ? (du coup on la vire des meta et on la parse par le filename)
- on pourra faire des index éditorials, rien nous en empeche en fait. que ce soit sans date (genre content/posts/fr/js/) ou ailleurs.

**Comment by lionelB** [comment]
:+1 pour la mise à plat avec date 
pour les index éditoriaux, il suffira d'utiliser les mots clés du coup... c'est cool !

**Comment by MoOx** [comment]
en plus on pourrait faire ca vite fait avec des redirections dégeux pour le moment

https://github.com/aymericbeaumet/metalsmith-redirect

**Comment by Nyalab** [comment]
perso, je trouve que c'est très bien comme c'est maintenant, peut être réorganiser un peu et faire des redirections comme tu dis @MoOx, mais un dossier par thème, c'est bien et ça permet de faire un index comme on le prévoit.

**Comment by magsout** [comment]
Par grosse thématique:
- Backend
   - JS
   - PHP
- frontend
   - JS
   - CSS
   - HTML
- env

**Comment by MoOx** [comment]
et un post sur une app isomorphique, tu le met où ?

**Comment by magsout** [comment]
c'est coté serveur, donc backend, non ?

**Comment by Nyalab** [comment]
bah nan, dans `js`

pas besoin de `backend`, `frontend` imho

**Comment by kud** [comment]
useless le backend/frontend.

**Comment by MoOx** [comment]
bon j'ai réfléchit et en fait, on aura souvent des cas "pénibles".
Donc je pense qu'on pourrait faire une règle bête: si le sujet à l'air conséquent, on créé un niveau dédié.
Exemples:

- posts/npm/*
- posts/grunt/*
- posts/semver/*
- posts/makefile/*
etc

Finalement c'est pas con et simple à la fois vous en pensez quoi ?

Toutes les url type "Introduction à *" ou "* c'est quoi", on les bouge en racine de ces "catégories" en question, puis les sous posts (exemple pour npm, le post sur napa) on le met dedans.

Ensuite pour les posts plutôt génériques "ex: array reduce javascript", on reste sur du simple: exemple /posts/js

Pour le "edito" faudrait trouver un fourre tout (post webcompat par exemple et le dev heiseinberg à venir)

Vous pensez quoi de toute ça ?

**Comment by Nyalab** [comment]
totalement d'accord avec ta simplicité @MoOx

**Comment by magsout** [comment]
:+1:

**Comment by Macxim** [comment]
Nickel :+1:

**Comment by kud** [comment]
Là, come ça, pas d'avis.

**Comment by MoOx** [comment]
Je m'occuperais de faire des redirections lors du passage en .io comme expliqué ci dessus.
