### ISSUE TITLE
Changer l'avatar Twitter

### ISSUE THREAD

**Issue by kud** [putaindecode/organisation#37]
Je fatigue de notre avatar sur twitter. Pourrions-nous pas le _flatiser_ (no moaaar gradient) ?

**Comment by MoOx** [comment]
je l'ai changé récemment. C'est toujours d'actu ?

**Comment by kud** [comment]
Je pense oui. :)

**Comment by MoOx** [comment]
ok, pr à voir sur le site donc, avec si besoin création d'image avec un suffix -twitter. par exemple.
