### ISSUE TITLE
Multi-repository sucks ass

### ISSUE THREAD

**Issue by Nyalab** [putaindecode/organisation#38]
Je trouve ça naze au final d'avoir plusieurs repo "organisation", "proposition-de-post", "putaindecode.fr".

Je n'arrive pas à avoir une vue d'ensemble, aller sur plusieurs repo et voir les issues de chacun, c'est naze. Vu le nombre que nous avons, ça ne surchargerait pas, et on en oublierait pas (ce qui est le cas aujourd'hui, il n'y a qu'à voir les topics dans orga). Les tables rondes par contre se justifient je pense, si vous voulez faire un site à part par ex.

Je propose de tout passer sur "putaindecode.fr", et d'utiliser des tags "proposition de post", "organisation", ...

Qu'en pensez-vous ?

La chocolatine masquée.

**Comment by MoOx** [comment]
Les propals sont depuis un moment sur le repo p!.
L'orga doit selon moi rester à part mais je suis pas fermé. Je ferme vu que personne réagit, si vous voulez relancer le débat, y'a un bouton "Reopen issue" :)

**Comment by kud** [comment]
+1 pour l'orga à part.
