### ISSUE TITLE
.fr -> .io/fr + création post en

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#39]
On se posait la question, on va le faire !

Vous pensez quoi qu'on reste simple avec .io/{lang}/posts/* ?

https://twitter.com/buttahz/status/598457945903398912

Comme ça si des gens veulent traduire en jap ou russe, on est bon ?
Si oui on passe tout le repo en "en" + README.{lang}.md + arbo à refaire par lang.

Moi je suis sur chaud.

**Comment by kud** [comment]
Très bien.

**Comment by madx** [comment]
Ça me va

**Comment by MoOx** [comment]
pour le seo, je propose de bouger le .fr sur un serveur qui supporte les redir (genre mon simple hosting chez gandi ou ailleurs) et de foutre un htacess qui redirigera sur .io/fr/*
Au passage on pourrait faire les redir lié à #35

**Comment by kud** [comment]
Yep.

**Comment by Nyalab** [comment]
lol

**Comment by MoOx** [comment]
merci de ta contribution sébastien.

**Comment by Nyalab** [comment]
non mais on doit avoir trop de posts en fr ou avoir un site parfait qui nous convient à tous ; j'ai du rater un truc en fait :trollface:

**Comment by MoOx** [comment]
j'ai pas compris ce que t'as dit.
Tu penses que c'est une idée nul ?
Peux-tu développer ?

**Comment by Nyalab** [comment]
c'était juste une ~réflexion~, je trouve pas qu'on fasse assez de posts en français pour tenir un rythme en anglais, ou alors que le temps passé pourrait plutôt l'être pour améliorer le site

après, chacun contribue à sa manière hein

**Comment by MoOx** [comment]
> après, chacun contribue à sa manière hein

Clairement oui.

@bloodyowl et moi sommes chaud pour faire plus que des posts en 2 langs à partir de maintenant et @skinnyfoetusboy est partie pour faire quelques trads.

**Comment by Nyalab** [comment]
oui, c'était juste pas du tout l'idée de lancement de p!, je vois pas trop l'intérêt à part la fame en l'occurence ; mébon

**Comment by MoOx** [comment]
on en avait parlé dès le début en disant qu'on verrait plus tard cela dit. Je pense pas dire de connerie là :)

**Comment by MoOx** [comment]
Si on fait ça, faudra sacrément réfléchir à une homepage.

**Comment by Macxim** [comment]
Moi ça me dit bien aussi. :+1:

**Comment by lionelB** [comment]
Hello,  

j'ai moyen envie de faire des posts en en+fr  mais si je pense que c'est une bonne idée de passé le site en multi langues notamment pour pouvoir traduire certains posts.

C'est quoi le plan avec le site en EN ? Créer aussi une communauté ? Faire des posts de qualités parceq'en EN y'a que des trucs de noob ? 

Si le but c'est crée un communauté et allez un peu plus loin (formation, biz...) Je pense que ça serait plus pertinent de consolider le FR avant d'attaquer EN.

TL;DR je suis pas contre si c'est pour avec quelque post EN qui ont pas vraiment d'équivalent EN.

**Comment by MoOx** [comment]
> C'est quoi le plan avec le site en EN ? Créer aussi une communauté ? Faire des posts de qualités parceq'en EN y'a que des trucs de noob ? 

Partager du savoir et de l'xp tout simplement.

L'idée n'est pas biz, c'est juste déveloper le concept de p!. Certains de nos posts n'ont pas vraiment d'équivalent EN je pense. Après personne sera obligé de faire ses posts en 2 langues bien entendu, des gens pourrons les traduire.

**Comment by kud** [comment]
Personne n'est obligée de traduire ses propres posts. C'est juste laisser une liberté qu'on n'avait pas avant, en mettant dans l'url la langue et un fichier associé à chaque langue pour chaque post.

**Comment by kud** [comment]
Du coup, le repo `putaindecode.fr` nommé comme ça ne va plus avoir lieux d'être. Je pense qu'on aurait dû / devrait garder ce repo nommé `website`.

**Comment by MoOx** [comment]
Bah on renommera putaindecode.io ?

**Comment by kud** [comment]
Le souci, c'est que cela dépend alors à chaque fois du nom de domaine. Alors que website est générique.

**Comment by MoOx** [comment]
en même temps on va pas changer de nom de domaine tous les 4 matins...

**Comment by MoOx** [comment]
Des idées pour la home du coup ?
On fera les équivalents en/fr sur .io/fr .io/en, mais du coup on mettrait quoi sur .io/ ?

Une grosse image hero avec une petit phrase en plusieurs langues ?

Le logo et le titre "Putain de code !" en gros avec les traductions dans plusieurs langues genre "fucking code !" qui link vers les langues respectives ?

Puis dessous tous les avatars des contributeurs ? Et éventuellement le lien vers gitter (on pourrait imaginer renommer /public en #putaindecode/fr et créer un #putaindecode/en ?

i18n all the things dudes.

**Comment by kud** [comment]
Je ne suis pas pour traduire notre groupe. "Putain de code" est son nom. "Putain de" sonne vraiment français, c'est pour moi la marque de fabrique quelque part.

**Comment by skinnyfoetusboy** [comment]
De toute façon, avant de sortir le truc en EN, il va nous falloir un petit backlog de sécurité de ~4-5 articles traduits, histoire de tenir un peu le contenu dès le départ.
L'approche Netflix, quoi.

**Comment by MoOx** [comment]
Je disais traduire pour faire un effet typographique et qu'en même temps un english qui arrive comprenne. Ca serait sur la home pour faire jolie. Le site serait bien putaindecode.io avec notre identité "Putain de code!" sur tout le site. Ca ne changerait pas.

Je pensais à ce genre d'effet 

![](https://d13yacurqjgara.cloudfront.net/users/146694/screenshots/1137497/47_1x.png)
![](http://www.anthonymatula.com/blog/imgbank/wordle_am.jpg)

avec un gros PUTAIN DE CODE au milieu.

@skinnyfoetusboy ouais j'ai 3 trads en court, on sera bon. De toute façon il faudra un peu de temps avant que ça s'installe c'est sur.

Cela dit, move fast & BREAKS THINGS (bon en fait il dit pas ça le monsieur http://zachholman.com/talk/move-fast-break-nothing/)

**Comment by skinnyfoetusboy** [comment]
"I don't write tests, tests are for people who write bugs" :trollface: 

Je dois terminer celui de @bloodyowl et ensuite je passerai sur un autre (hésite pas à me dire ceux sur lesquels tu bosses, histoire qu'on finisse pas par traduire le même article)

**Comment by MoOx** [comment]
mes 2 derniers posts, et ceux à venir :)

**Comment by MoOx** [comment]
A part Nyalab "pas trop chaud" mais pas contre, je vois personne qui exprime une réticence, au contraire, ceux que ça intéresse sont entousiate. Je propose de me pencher dessus ça la semaine prochaine en commencant par migrer le contenu actuel vers .io/fr/* (sans pour autant avoir de /en/). Ca sera l'étape 1 :)
Si vous n'êtes pas ok, faites le savoir d'ici là.
Perso, plus je vois un .fr, moins j'aime ^^

**Comment by kud** [comment]
Il faut surtout étudier les redirections pour éviter de perdre en SEO.

**Comment by MoOx** [comment]
C'est un détail ça. On en a déjà parlé je mettrais un htaccess sur mon serv et on en parle plus ;)
Au passage je réajusterais quelques urls pour ranger vu qu'on trouve pas de solutions ultimes pour la #35

**Comment by MoOx** [comment]
Petit point:

on mélangera pas le site en/fr en fait
on aurait une home qui te forward selon ton choix
puis des liens sur le post fr genre “this post also exists in english"
et reverse sur le post en autre langues
pas plus

du coup un mec fr
il arrive sur un psot voit “this post also exists in english" dans le header du post
il se dit “ah cool"

on met le principe inverse sur les posts dans d'autres langues.

voyez le truc ? moi je le vois comme ça

Note: vu que l'idée de base du projet étant fr, on doit avoir tous les posts en fr, les trads en d'autres langues étant optionel.

là nos followers sont fr
on va pas leur parler en anglais, j'ouvre donc une issue pour les handle twitter qui font débat sur le chan.

**Comment by Nyalab** [comment]
nickel, juste, privilégiez toujours le français

**Comment by kud** [comment]
Avec @MoOx, ça va être difficile, @Nyalab.

**Comment by MoOx** [comment]
Bon on valide ça ?

Au départ ok on a voulu se focus sur fr vu le manque de ressources. Mais là à lire certains avis sur d'autres endroits (d'autres issues, chan etc) vis-à-vis de ce choix (s'ouvrir à d'autres langues), j'ai l'impression de voir certains pas vraiment en phase avec ce choix alors qu'on oblige personne à faire d'autres langues. Si ça vous plait pas, vous faites des posts fr et voilà tout ? Pourquoi s'y opposer (ou du moins exprimer que c'est pas une bonne idée selon vous) ?
Quel serait le problème à part l'éventuel argument "vous allez délaisser le site fr" (et ça vu les prérequis qu'un post doit être forcément en fr, je vois pas le soucis).

**Comment by kud** [comment]
post fr obligatoire qu'importe la langue. Le reste, c'est à chacun (ou autre) de faire la traduction. Ca irait ça donc ?

**Comment by magsout** [comment]
>post fr obligatoire qu'importe la langue. Le reste, c'est à chacun (ou autre) de faire la traduction. Ca irait ça donc ?

parfait pour ma part.

**Comment by lionelB** [comment]
ok pour moi

**Comment by Nyalab** [comment]
je ne m'y oppose pas, je dis pareil que toi, go. Puis même pour du fr, je préfère un domaine en .io :smile:

**Comment by kud** [comment]
Le .io était plus ou moins acté de toute façon non ?

**Comment by MoOx** [comment]
J'ai commencé à modifier le site dans ce sens (wip local).
Dans tous les cas je vois .io/{lang}

Je vois 2 axes possibles (pour faire simple) qui se répèrcuteront sur #44 et #45 :
- soit on fait fr + (en && le reste)
  - fr
    - slack fr-general, fr-random
    - twitter @putaindecode_fr
  - en && le reste
    - slack general, random
    - twitter @putaindecode
- soit on fait fr + en + ...
  - {lang}*-(general | random}
  - @putaindecode_{lang} (mais là je dis stop, je pense on est tous d'accord)

Je vote sur fr + (en && le reste), "le reste" étant probalement très minoritaire et qui sera juste "une tolérance" pour le moment

J'ai besoin qu'on soit en phase car je veux finir ça et pousser le site asap qu'on itère doucement mais surement. Euh non l'inverse :)

**Comment by kud** [comment]
```
    fr
        slack fr-general, fr-random
        twitter @putaindecode_fr
    en && le reste
        slack general, random
        twitter @putaindecode
```
Ca m'parait bien ça.

Après faudrait que les gens prennent l'habitude de parler dans le bon channel.

**Comment by Nyalab** [comment]
je vote pour l'inverse, les fr par défaut, et on précise quand c'est en (on voit bien que quand les gens débarquent sur slack ils parlent direct)

**Comment by lionelB** [comment]
:+1:  avec @Nyalab

**Comment by MoOx** [comment]
=> https://github.com/putaindecode/putaindecode.fr/issues/487
