### ISSUE TITLE
should i stay or should i go

### ISSUE THREAD

**Issue by Nyalab** [putaindecode/organisation#40]
vous avez le mail, et en fait personne a envie d'argumenter, vous avez juste à mettre :+1: ou :-1: pour que je reste ou que je parte (osef de vos arguments), prenez ces 3 secondes pour voter, et j'vous fais plus chier après

**Comment by lionelB** [comment]
:heart:

**Comment by kud** [comment]
Another drama. Anyway. :+1:

On 26 May 2015 at 10:48, Lionel <notifications@github.com> wrote:

> [image: :heart:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/organisation/issues/40#issuecomment-105448984>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by MoOx** [comment]
👍🏻

--
Maxime Thirouin,
Front-end web developer

+33 6 78 13 54 39 <tel:+33678135439>   |   http://moox.io/ <http://moox.io/>

**Comment by madx** [comment]
Arrête de faire ton attention whore

:+1:

**Comment by MoOx** [comment]
Une issue rien que pour ça il fait juste chier le mec.

**Comment by Macxim** [comment]
:+1:

**Comment by kud** [comment]
Il voulait juste se faire mousser le mec. 

![](http://media.giphy.com/media/y9WlUlUtbVofS/giphy.gif)

**Comment by bloodyowl** [comment]
:+1:
![](http://media.giphy.com/media/Lxr5ElPrLPOoM/giphy.gif)

**Comment by magsout** [comment]
:+1:

**Comment by Nyalab** [comment]
merci les mecs, j'vais essayer
