### ISSUE TITLE
Post minimal guidelines

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#41]
(je repost à l'endroit plus approprié)

Je propose qu'on se fasse des guidelines pour la rédaction de posts. Chaque post devra respecter ces règles:

- Un post ne doit pas contenir de formule personnel ("Je pense que", "je vous nique tous avant la mise en prod le vendredi" etc). Une des raisons _selon moi_ (BAM ça passe pas ça par exemple). Puisque revu et corrigé par une groupe -- parenthèse: dans ce sens, on devrait diminuer la taille du bloc de l'auteur en fin de post, car au final, le lecteur s'en branle de qui c'est qui écrit nan ?

En fait je comptais en mettre plusieurs, mais j'ai l'impression que la règle ci dessus ferait indirectement beaucoup de bien sur les formulations du genre "j'encule les nazi et les pd", puis ça devrait être écrit "On encule..." et que à la revu il faut un minimum d'approbation. 

Ma règle je l'aime bien sans y avoir trop réfléchi car à elle toute seul, elle préviendrait pas mal de choses.
Vous avez le droit de faire à la @Nyalab: :+1: ou :-1:  ou éventuellement :fuck: ou :ragequit:

Je viens de penser à ça aussi

- En cas de "litige", on doit revoir un point si plus de la moitié des personnes qui s'expriment pensent que le point en question mérite d'être revu à raison d'un minimum de 3 personnes.

Ca reste simple et pas contraignant (j'ai pas dit genre si plus de 1 sur 10 :D)

**Comment by kud** [comment]
Proposition intéressante par contre, j'ai besoin de temps pour réfléchir et dire ce que j'en pense.

**Comment by lionelB** [comment]
:metal: -  :fu: = :+1: 
Au pire on pourra toujours changer

**Comment by MoOx** [comment]
bump

**Comment by magsout** [comment]
Moi ça me va. Je pratique d'ailleurs déjà ces guidelines.

**Comment by Nyalab** [comment]
nan, je comprends pas, c'est toujours des posts écrits par une personne, juste validés par une communauté, mais au contraire, les prises de positions sont nécessaires, on utilise pas tous les mêmes technos, pas les mêmes avis, etc.

et par contre je suis ok pour des guidelines genre 80 chars, peut être pas de listes imbriquées, etc,.

**Comment by MoOx** [comment]
C'est pas car c'est écrit par une personne que t'es obligé de mettre "moi je". Si tu regardes mes derniers posts et ceux de magsout, je suis sur que t'as même pas fait attention à ce "détail".

**Comment by MoOx** [comment]
Note: les histoires de 80chars & co étant déjà dans le CONTRIBUTING.md

**Comment by kud** [comment]
Je ne suis pas pour le contre "je".

**Comment by MoOx** [comment]
@kud tu as dit que des journaux écrivent à la première personne, je ne crois pas avoir vu ça encore. Donc si tu as des liens je suis preneur. Pour un blog évidemment ça ne s'applique pas puisque c'est un journal personnel.
Le but n'étant pas de juste "ne plus avoir de je" mais, comme j'ai pris le temps de l'expliquer, d'éviter des tournures problématiques. Puis dans le fond le lecteur ils s'en branlent de celui qui écrit, il cherche une info. On peut très bien utiliser le "on" ou "nous" en contextualisant.

**Comment by bloodyowl** [comment]
à mon sens pareil, on doit pas empêcher le "je", perso je l'utilise rarement dans les articles, mais il doit rester disponible pour les prises de position.

**Comment by MoOx** [comment]
up pour les avis des gens qui donnent pas leur avis.

**Comment by Macxim** [comment]
Je pense qu'on peut rester impersonnel sur la majorité d'un article. Mais on n'est pas non plus obligé pour autant de bannir le "je". Si l'auteur veut donner son avis sur un truc précis, qu'il le fasse.

Ça peut aussi provoquer des débats, des conversations, de l'interaction avec les lecteurs, ce qui est une bonne chose.

**Comment by MoOx** [comment]
On pourrait donc recommander de limiter la première personne au prise de position?
