### ISSUE TITLE
 Owners definition

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#42]
On **pourrait** poser la chose suivante : 

owners = 8 top contribs (contrib: commit + issue comments) sur les 12 derniers mois en date des noms de domaines.

C'est simple et ça évite de demander et on a aucune rancune à retirer les inactifs des owners.

**En l'état ça ne changerait rien (ce n'est surtout pas le but) et ne demande pas plus de travail de qui que ce soit.**

:+1: || :-1: || commentaire pour discuter de cette idée

**Comment by kud** [comment]
Besoin de réflexion pour ma part avant jugement.

**Comment by lionelB** [comment]
je suis ok pour essayer même si j'ai du mal à voir si c'est un bon système ou pas. 
(genre je suis du genre à faire du micro commit du coup ça booste le score vs un gros commit bien moche) alors qu'au final c'est aussi les interactions qui comptent...

**Comment by madx** [comment]
Assez sceptique sur les commits, car comme le dit @lionelB ça dépend de leur contenu. Par contre sur l'idée du "Top 8 Contibs" je suis tout à fait pour.

**Comment by Nyalab** [comment]
whatever you want

**Comment by MoOx** [comment]
Qui ne dit mot consent.

**Comment by Nyalab** [comment]
à noter que @kud réfléchit depuis le 26 mai ; le type doit être bloqué en position du lotus et être passé au niveau supérieur de super saiyan

**Comment by kud** [comment]
C'est une haute question intellectuelle, tu sais.
