### ISSUE TITLE
Changer le top contributeurs ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#43]
On voit toujours les mêmes têtes.

**Comment by MoOx** [comment]
Oups. j'ai cliquer trop vite sur enter lel. Je reprends.

**Comment by MoOx** [comment]
On voit toujours les mêmes têtes donc. Ce qui m'embete le plus c'est les mec en bas.
J'allais dire "on réduit" le nombre mais si je recoupe avec #42 on va retomber sur le crew (dans un sens ca serait logique). Ça m'irait mais je sais pas ce que vous en pensez.
Comme d'hab je pose des questions pour améliorer le rendu du site en fait, rien de plus.

**Comment by kud** [comment]
J'pense qu'il ne faut pas se leurrer, on sait déjà qui est dans le core. On devrait n'avoir que ces gens là, et voilà.

**Comment by kud** [comment]
Si un mec veut rentrer dans le game, on en discute et on fait en conséquence.

**Comment by lionelB** [comment]
Moi ca me pose pas de pb de voit toujours les même.
D'ailleurs, je vois que pour quelques commit de plus, je vais pouvoir griller @Nyalab :yum:

**Comment by madx** [comment]
Oui c'est logique, si les owners sont les top contribs, on voit toujours les owners sur le top des contibuteurs :D 

Ça me dérange pas du tout

**Comment by Nyalab** [comment]
perso je trouve pas ça dérangeant, mais si ça te gêne vraiment, pourquoi ne pas le faire sur 7/14/30/60 jours glissants, pour que les têtes tournent un peu quand on a des posts de contributeurs externe ?

ou alors carrément les 5 derniers contributeurs, enfin, un truc qui change un peu, même si au fond je vois pas le souci

**Comment by magsout** [comment]
en l'état ça me dérange pas plus que ça.

**Comment by MoOx** [comment]
Cf https://github.com/putaindecode/putaindecode.fr/issues/485
