### ISSUE TITLE
handle twitter pour passage .io

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#44]
Je résume l'idée du truc

.io/fr/* contenu actuel
.io/{lang}/* contenu optionel

`@putaindecode` est acutellement notre handle twitter. Normal
Avec la création de contenu multilangues, on aurait un autre compte, lui EN uniquement qui relaiera les traductions (surement majoritairement en, mais sais on jamais, @Macxim a déjà un post ES sous le coude (qui sera en fr, en, es)).

Du coup il faut un autre handle twitter.
Perso pour faire "simple" je procèdérais ainsi:

`@putaindecode` fr (main) + `@putaindecode_io` pour les trads.

@kud pense que c'est très abérrant d'avoir un compte twitter `@putaindecode_io` puisque le _io selon lui ne correspond à rien pour un handle tiwtter (je le laisse s'exprimer ci besoin).

Perso je trouve un `@putaindecode_en` assez naze, ne serait ce que visuellement. `@putaindecode_EN` c'est encore plus pourri selon moi.

Les votes sont ouvert (fr + i18n)

- `@putaindecode`
- `@putaindecode` + `@putaindecode_io`
- `@putaindecode` + `@putaindecode_en`
- `@putaindecode` + `@putaindecode_EN`
- `@putaindecode_fr` + `@putaindecode`
- `@putaindecode_fr` + `@putaindecode_en`
- `@putaindecode_EN` + `@putaindecode_EN`
- `@putaindecode` + `@putaindecode_i18n`

**Comment by MoOx** [comment]
:+1:  `@putaindecode` + `@putaindecode_io`

**Comment by kud** [comment]
/très aberrant/aberrant/s

Plusieurs solutions à mon sens : 

## Solution 1

On garde `@putaindecode` et on fait du multilangue dessus

## Solution 2

`@putaindecode` pour le français et `@putaindecode_EN` ou `@putaindecode_en` pour l'anglais


## Solution 3

`@putaindecode_fr` pour le français et `@putaindecode` pour l'anglais


## Solution 4 (sans plus-

`@putaindecode` pour le français et `@putaindecode_i18n` pour l'anglais

---

Je ne suis pas d'accord pour le `_io` car il ne veut rien dire, il ne précise pas en quoi on va parler anglais sauf si on considère que l'océen indien parle anglais. De plus, `.io` regroupera toutes les langues. Dans ce cas, pourquoi n'aurions nous pas aussi le français dans `.io` #cohérence

**Comment by MoOx** [comment]
Fait un vote simple stp. Donne un choix pour faciliter les échanges.
J'ai déjà posé les solutions que tu mentionnes et je pense qu'elles sont claires en soit.

Tout le monde dans notre milieu sait à quoi _io fait référence. Nous pose pas des phrases avec des hastags digne de mokoloco :D

Cela dit on pourrait imaginer n'avoir qu'un compte meme si je ne penses pas que ca soit une bonne idée. Je le rajoute dans les propotions.

**Comment by kud** [comment]
J'ai déjà fait un vote.

**Comment by MoOx** [comment]
Ok tu l'as rajouté après coup.

**Comment by bloodyowl** [comment]
:+1: avec @kud: @putaindecode_fr & @putaindecode

**Comment by madx** [comment]
Pourquoi pas juste @putaindecode et #en, #fr, #es pour les posts. Les gens peuvent se foutre un filtre pour suivre ce qui les intéresse, on garde toute l'info au même endroit.

**Comment by Macxim** [comment]
Je sais que `domain name != Twitter handle` mais pour plus de cohérence, si on utilise `.io` pour toutes les langues, pour tous les posts, je ne vois pas trop pourquoi on devrait créer un autre compte Twitter avec un `_fr/_FR` ou un `_en/_EN`. Puisqu'on ne retrouvera ça nulle part sur le site.

Donc pour moi, ce serait juste @putaindecode. Ce sera aussi plus simple à maintenir.

**Comment by kud** [comment]
+1 pour @Macxim et @madx. Un seul compte, des hashtags.

**Comment by MoOx** [comment]
Très peu de gens ont des clients qui permettent de filtrer correctement il me semble.

**Comment by Nyalab** [comment]
lel ; personne ne filtre sur les hashtags, et si ceux qui écrivent en anglais veulent avoir des followers, imho ; dès qu'ils vont vous voir tweeter 2/3 trucs en fr, ils vont unfollow

**Comment by Macxim** [comment]
Oui, vous avez raison sur ces points-là :confused:

**Comment by kud** [comment]
donc je reste sur `_fr`.

**Comment by magsout** [comment]
@putaindecode + @putaindecode_io

**Comment by lionelB** [comment]
@putaindecode + @putaindecode_hq
J'aime pas du tout le   `_xx` et alors le ponpom passer putaindecode en anglais, un site d'entraide en francais...  

je suis plutôt pour trouver un nouveau nom de compte EN et tant qu'à faire, autant vouloir se la péter IT de san francisco vu que le plan c'est de conquérir le monde !

**Comment by kud** [comment]
+1 par rapport au franco-français proné par @lionelB. Et "hq" est pas désagréable.

**Comment by MoOx** [comment]
_hq ça correspond à quoi ?

Je ne vois pas vraiment l'interet de "refaire" une autre identité, le but étant d'avoir un lot de ressource de qualité à partager. fr/en/whatever dans le fond qu'est ce qu'on s'en fou ?

Je vais continuer sur ce sujet dans la  #39, restons concentré ici sur l'hypothèse du fr + multi pour le choix.

**Comment by lionelB** [comment]
> _hq ça correspond à quoi ?

HeadQuarter

**Comment by MoOx** [comment]
hum ouais je vois. J'adhère pas :)

**Comment by lionelB** [comment]
> A headquarters is the entity at the top of a corporation that takes full responsibility for the overall success of the corporation 
https://en.wikipedia.org/wiki/Headquarters

Au cas où, ca n'a rien a voir avec du militaire en EN

**Comment by MoOx** [comment]
Non mais j'avais bien compris. Je trouve ça juste cheloo pour le coup.

**Comment by lionelB** [comment]
pour le vote `@putaindecode` + `@putaindecode_io` si le hq passe pas

**Comment by kud** [comment]
J'ai vraiment du mal avec le `_io` qui veut rien dire pour moi sur un compte twitter (je parle pas du nom de domaine). Si après, on est plusieurs à penser que c'est le bon choix, go. ;)

**Comment by madx** [comment]
@putaindecode_intl ?

--
François Vaux
http://madx.me/

**Comment by kud** [comment]
J'avais proposé _i18n à ce sujet @madx

**Comment by madx** [comment]
I18n = internationalisation
Intl = international

Pas tout à fait pareil sémantiquement en fait

--
François Vaux
http://madx.me/

**Comment by kud** [comment]
D'accord. Bref, dans tous les cas, ça ne plaira pas aux autres. ;)

2015-06-01 10:38 GMT+02:00 François Vaux <notifications@github.com>:

> I18n = internationalisation
> Intl = international
>
> Pas tout à fait pareil sémantiquement en fait
>
> --
> François Vaux
> http://madx.me/
> Le 1 juin 2015 10:36 AM, "Erwänn Mest" <notifications@github.com> a écrit
> :
>
> > J'avais proposé _i18n à ce sujet @madx <https://github.com/madx>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/putaindecode/organisation/issues/44#issuecomment-107363752
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/organisation/issues/44#issuecomment-107365338>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by Nyalab** [comment]
bon vous êtes relous, go @putaindecode et @putaindecode_fr c'est bon

**Comment by kud** [comment]
lolz

**Comment by lionelB** [comment]
> bon vous êtes relous, go @putaindecode et @putaindecode_fr c'est bon

NAN c'est toi le relou, go @putaindecode et __@putaindecode_[en|io|hq|lol]__

**Comment by MoOx** [comment]
Punaise. Personne est relou, on fait un vote. On comptera quand tout le monde aura vôté, ou on s'arretera avec le nombre de votant en l'état qu'on on attaquera ce changement.
D'ailleurs on devrait poser un délais dans "les règles" :D "Après un détais de X temps pour un vote ou review, on peut considérer la discussion terminé". J'aime bien les règles.

**Comment by lionelB** [comment]
Désolé mon message précédent était sur le ton de la rigolade

**Comment by kud** [comment]
![](https://pbs.twimg.com/media/Br9YOFXIMAAUbpb.jpg)

**Comment by MoOx** [comment]
Nan mais y'a pas de soucis, c'est pas interdit hein :)
Sinon je vous aurez insulté de fdp™ (© fils de prout)

**Comment by MoOx** [comment]
@putaindecode + @putaindecode_fr ressorte en majorité.
Si on fait ça, je propose qu'on renomme le putaindecode du moment en _fr (vu que les followers viennent de là et qu'on crée un nouveau putaindecode qui lui sera i18n, cf https://github.com/putaindecode/organisation/issues/39#issuecomment-111519534

**Comment by kud** [comment]
Oui

**Comment by MoOx** [comment]
Done avec `@putaindecode + @putaindecode_fr`

https://twitter.com/putaindecode_fr/status/655825900244770817

**Comment by Nyalab** [comment]
JE CRIE AU SCANDALE (même si osef)
