### ISSUE TITLE
Slack : définition des salons

### ISSUE THREAD

**Issue by kud** [putaindecode/organisation#45]
Hello,

Suite à la migration sur Slack ainsi qu'à l'ouverture de pas mal de salons. Je propose que l'on définisse ici l'intérêt de chacun et voir si on les garde tous ou si on en supprime.

Les salons privés ne sont pas à discuter je pense, passons au public. 

```
- website
- fr
- fr-js
- fr-css
- fr-chat
- music
- meta
- general
```

Il est possible que j'en ai oublié.

## website

pour discuter du site en soi, right?

## fr

je ne sais pas trop à quoi ça équivaut, est-ce juste "français" et dans ce cas, on peut virer musique, chat, ou est-ce que c'est technique sauf js, css ?

## fr-js

ok je pense

## fr-css

j'aurais plutôt généraliser ça à un truc comme "intégration" mais pas limité à css, car html est nécessaire sauf si on crée un salon html en conséquence ?

## fr-chat

dépendra du niveau de discussions des autres salons

## music

je l'aurais bien mergé dans chat en fait, on a pas forcément besoin d'en faire un salon spécifique

## meta

j'avoue j'ai toujours pas compris l'objectif de ce chat

## general

apparemment par défaut ? dans ce cas là, ce serait peut-être notre "en" en fait

---

A vous !

**Comment by MoOx** [comment]
imo
 
- fr (code)
- fr-random (non code)
- meta (discuter de ca justement, de l'orga de slack) mais on peut faire ca dans owners)
- general (entry)

quand migration .io

- en
- en-random 

le reste ca dégage imo

**Comment by kud** [comment]
Quel intérêt de "en" quand y'a déjà (apparemment imposé par slack) "general" ?

Okay pour "fr" et "fr-random".

"meta" j'en vois pas l'utilité, le chat privé et ce repo servent à ça je pense.

Carrément ok pour virer les autres.

**Comment by Macxim** [comment]
Pareil que @MoOx.
Et donc virer #meta.

**Comment by Nyalab** [comment]
#general (point d'entrée où on redirige, comme sur le slack babel)
#fr-dev
#fr-random
#en-dev
#en-random

**Comment by kud** [comment]
dev ? quel intérêt ?

On est tous en revanche d'accord sur la simplicité, dev / chat.

**Comment by Nyalab** [comment]
bah #fr c'est pas assez parlant, #fr-dev, oui ou alors #fr-web j'sais pas quoi

**Comment by kud** [comment]
D'accord

**Comment by lionelB** [comment]
:fu: avec @Nyalab

**Comment by kud** [comment]
Bon, ok avec @Nyalab pour le moment.

**Comment by MoOx** [comment]
Jme fais chier en sav alors j'ai viré meta et website.
Je pense qu'on rename f ren fr-random et fr-js en fr-general et qu'on archive fr-css.
fr/fr-dev/fr-general, mem combat. En fait je pense sue le combo general/random c pas mal. Apres appeler ca dev ca a le merite d'etre clair sur le but

**Comment by kud** [comment]
Okay pour `fr-random` et `fr-general`. Par contre, j'avais créé un salon `fr-random` avant du coup, j'arrive pas à mettre `fr-js` en `fr-general` là. :/

**Comment by kud** [comment]
On est ok pour : 

- fr-general
- fr-random
- general
- random

?

**Comment by kud** [comment]
Apparemment il faut qu'on désarchive random, impossible de renommer un salon déjà archivé.

**Comment by kud** [comment]
Ah pardon, on peut aller les supprimer, je vais faire ça. ^^

**Comment by Nyalab** [comment]
on a quand même littéralement 0 personne qui parle anglais du coup, je verrais plus

* general
* random
* en-general
* en-random

**Comment by kud** [comment]
Le truc mon loulou, c'est que de base, le salon par défaut est `general`. Si tu arrives et que tu vois que ça parle français alors que tu es anglais ou une autre langue...

**Comment by kud** [comment]
J'ai fait pour le moment le nécessaire, j'attends de savoir si @madx veut bien qu'on aille sur `fr-random` pour music, et si on garde `fr-` ou `en-`.

**Comment by bloodyowl** [comment]
:+1: avec @Nyalab, le site est francophone. les anglophones qui viendront verront bien à gauche un "en-general" & "en-random"

**Comment by kud** [comment]
`fr-` | `en-`
---|---
@Nyalab | 
@bloodyowl |
 | @kud
 | @MoOx

**Comment by kud** [comment]
Un autre avis ? poke @putaindecode/owners

**Comment by kud** [comment]
Oui on a pas beaucoup d'anglais, que des français, mais cf https://github.com/putaindecode/organisation/issues/45#issuecomment-111495163

**Comment by Nyalab** [comment]
se soucier des trucs hypothétiques ça sert à rien, on avisera le jour où on verra un anglais arriver et se barrer ou alors se plaindre ... je mettrais même juste un chan #english sans rien différencier entre dev et random pour le moment, et MÊME JE METTRAIS PAS D ENGLISH TANT QU'ON A PAS LE SITE

**Comment by lionelB** [comment]
Puisqu'on peut changer d'avis je propose de mettre général et random et renommer les chan quand on aura le besoin

**Comment by lionelB** [comment]
dans mes bras @Nyalab

**Comment by kud** [comment]
pwouah donc random et general, et raüs l'anglais pour le moment ?

**Comment by MoOx** [comment]
fr-* + en-* + general qu'on laisse plutot vide en point d'entrée. On aura le meme point a geré avec la home global + home fr + home en

**Comment by kud** [comment]
dééééééééééééééééééémeeeeeeeeeeeerdeeeeeeeeeeez-vous.

![](http://i.giphy.com/3AIWph8KSF3l6.gif)

**Comment by ooflorent** [comment]
Sinon juste `#general` et `#random`.

**Comment by kud** [comment]
MAIS OUAIS MAIS OUAIS @ooflorent (yolo)

**Comment by MoOx** [comment]
Le .io est pres en local, just sayin. Je fini 2 trad et il sera là... Enfin faite ce que vous voulez mais j'espere que ca durera pas vu que le contenu en c genre le mois prochain ;)

**Comment by kud** [comment]
Donc on revient au sujet soit `fr-` soit `en-`.

**Comment by bloodyowl** [comment]
premature optimisation is the root of evil :)

**Comment by bloodyowl** [comment]
tant qu'on aura pas de users uniquement anglophones, ça sert à rien de faire ça

**Comment by kud** [comment]
Le ménage a été fait, plus qu'à (n|v)ous décider sur les noms des salons.

**Comment by magsout** [comment]
je partage l'avis de @ooflorent

**Comment by madx** [comment]
J'm'en bats les couilles, moi je préférais IRC !

![](
http://media.giphy.com/media/w2jw9fSHEdQis/giphy.gif)

**Comment by magsout** [comment]
![raining](https://cloud.githubusercontent.com/assets/1997108/8132193/382225e0-1120-11e5-8088-9d6f8a977d8a.gif)

**Comment by MoOx** [comment]
Tout ça recoupe à mon avis le #39 et #44. Je vais élaborder sur la #39 qu'on soit d'accord sur une façon de faire général, le reste suivra je pense.

**Comment by MoOx** [comment]
https://github.com/putaindecode/organisation/issues/39#issuecomment-111519534

**Comment by kud** [comment]
Pour l'instant, après avoir un essai `fr-`, les gens s'en battent les couilles de la langue, ils respectent juste le random / general.

**Comment by MoOx** [comment]
Un essai sur 2h un vendredi aprèm n'est pas suffisant imo.
De plus pense à la #39 puisque je bosse dessus. On aura du contenu en, sur un site en partie en, si des gens cliquent sur Slack ils vont partir directe. Sinon on ne met que slack sur la partie fr (même si je trouve ça dommage, c'est une option)...

**Comment by MoOx** [comment]
Bon là je trouve que comme c'est au final ça fonctionne et c'est pas mal, même si y'a quelques débordements, dans l'ensemble c'est bien le `#{lang}-(general|dev)`.
Je ferme faute de plus de retour.
