### ISSUE TITLE
Suppression de aliases mails

### ISSUE THREAD

**Issue by MoOx** [putaindecode/organisation#46]
Personne ne les utilise jamais, ils servent à rien je propose qu’on supprime les 

{member}@putaindecode.fr

On garde que les aliases genre team, jobs, twitter etc. Pas un gros changement en soit, vous en pensez quoi ?

(Ca facilitera la migration .io)

**Comment by kud** [comment]
Okay pour ça

**Comment by bloodyowl** [comment]
agreed

**Comment by Nyalab** [comment]
k

**Comment by lionelB** [comment]
oué d'ac

**Comment by MoOx** [comment]
On a donc maintenant sur putaindecode.io:

mail@, jobs@.

Les autres mails genre google@, twitter@ etc sont restés en .fr, redirect sur mail@ .io. A l'occassion je mettrais tous les comptes à jour et les virerais pour des mail+{service}@.
