### ISSUE TITLE
stylenext

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/organisation#47]
avec @MoOx on veut créer stylenext (petit toolkit pour avoir les features de cssnext avec les styles inlines): 

principalement:

- autoprefixing
- couleurs
- breakpoints?

questions:

- où créer le repo?
- autres features?

**Comment by kud** [comment]
Très intéressant. Tu as plusieurs possibilités pour le répo.

Soit d'abord putaindecode puis si ça prend de l'ampleur, une orga dédiée. Soit directement une orga dédiée. Disons que quand un projet est encore petit, j'ai tendance à croire qu'une orga est trop prétencieux pour commencer. A vous de voir.

Comme ça, j'ai pas d'idée pour d'autres features, tant que ça fait ce que j'ai avec cssnext, c'est nickel (pour moi ?).

Au pire, ça peut s'ajouter par la suite.

**Comment by MoOx** [comment]
je viens de faire le tour des feat de cssnext:
- ce qui touche les selecteurs -> OSEF
- ce qui touche les values: couleur 50%, préfixes 49%, le reste (font-variant)
- reste les media queries

du coup je vois

- un truc similair pour définir et appeler des custom media/element queries (on pourrait du coup avoir les éléments queries, plus pertinent encore que les breakpoints. A méditer). cf css-recipes-utils
- Pour les couleurs j'ai la main sur https://github.com/harthur/color, je pourrais bosser dessus pour apporter la meme api que les color() css 4 (eg: `color("#000").a(.6)`...) ça me parait pas con.
- autoprefixing le soucis est presque déjà résolu (sauf peut etre pour des trucs compliqués comme flex mais bon).
- math sur des unités de styles ? calc(width * 2 + "4px") ? On pourrait _pas_ simplement faire appel à la logique de mon https://github.com/MoOx/reduce-css-calc à voir si y'a besoin
- faut un reset globales ou un truc du genre à minima si on part du principe que on a plus de css du tout (on alors on provide un defaults.css qui serait un requirement qu'on introduit)
- des resets pour les buttons & co (cssrecipes-reset quoi)

Je compte maintenir cssnext (pas forcément le faire évoluer pour ne pas "perdre" trop de temps, mais vu que en l'état je suis pas marié avec react et que j'ai un ou 2 wordpress à côté, je vais pas drop cssnext pour autant). Le repo on pourrait presque le faire sur l'org cssnext. Ça fait un peu :trollface: mais ça me parait pas con non plus, surtout si on essayes de se calquer dessus pour garder une cohérence.
Ou alors fliptable et on fait stylenext. Après on peut surement trouver un nom moins troll, plus en réalité de la finalité: "styleutils" est libre sur npm.

```js
import {color, media} from "styleutils"

const transparentBlack = color.black.a(.4)
const sortOfPink = color.red.w("+10%")

// bon en fait avec react les element queries ca me parait compromis vu qu'on fait le rendu avant de savoir la taille que ca prends lol
const myMedia = {
  xl: "1000" //px ? em?
}

{
  media.width > myMedia.l && // window.innerWidth >= myMedia.l ?
  <Jumbotron styles={{
    ...media.portrait ? styles.portrait : {},
    ...media.width > myMedia.l ? styles.large : {},
    ...media.width > myMedia.xl ? styles.xl: {},
  }}/>
}
```

Convention sur les nommages des media: small ou s, etc ?

**Comment by MoOx** [comment]
on pourrait ajouter des helpers pour les animations p-e (déjà requestAnimationFrame)?

Après "styleutils" c'est pas très jolie comme nom.
stylenext ça fait trollesque.

Quelques idées:
- babelcss :trollface: 
- styleproof
- btts (back to the styles)
- styleinline
- styline
- lesstyle :trollface:
- morestyles
- stylittude
- objectivstyle (objectif: style :trollface: )
- styletrw (style the right way)
- withstyle

**Comment by MoOx** [comment]
- sstyle
- sstyles
- stylegold (not style shit)
- notcss

**Comment by MoOx** [comment]
Idea: a babel plugin to avoid having to write json like value

{
  prop: value1 value2,
}

Converted to 

{
  prop: "value1 value2",
}

This will need some deeper thoughts tho.

**Comment by MoOx** [comment]
`percentage(1/3)` => "33.333%"

**Comment by MoOx** [comment]
tu me dira que calc(1/3) fait déjà le taf :D

**Comment by MoOx** [comment]
Je me demande si des `rem(4)` => `4rem` ca peut etre une abstraction intéressante.
Le percentage reste pertinent (eg: border radius n'accepte pas de calc() ni d'int)
- {unit}(value):  `${ value }${ unit }`
- precent(value): `${ value*100 }%`

**Comment by MoOx** [comment]
Autre idée de nom `stile` (même prononciation que `style`)

**Comment by bloodyowl** [comment]
# api

## core

```javascript
import { createStyleSheet, rem, color, darken } from "stile"

const styles = createStyleSheet({
  title: {
    fontSize: rem(1.5),
    color: darken(color(255, 125, 125), .2),
  },
})
```


## react

```javascript
// app root
import { ResizeProvider } from "stile/react"

// the function child is just a workaround while 0.14 is not released
React.render(
  <ResizeProvider getViewport={({ width, height }) => width > 1000 ? "L" : "M"}>
    {() => <App />}
  </ResizeProvider>,
  mountNode
)

import { resizeable } from "stile/react"

@resizeable()
class Component {
  render() {
    const { viewport, viewportWidth, viewportHeight } = this.props
    return (
      <div
        style={{
          ...styles.component,
          ...viewport === "M" && styles.componentM,
        }}>
      </div>
    )
  }
}
```

**Comment by MoOx** [comment]
We could provide multiples part:

```js
import sx from "notcss"

sx.values(1,2,3) // 1 2 3
sx.list(1,2,3) // 1, 2, 3
sx.unit.rem() // or sx.{all units here}() ?

sx.color() // a color, then you can chain modifier on it sx.color(#fff).blackness() (darken is a pretty shitty and unclear name for a method on a color)
 // color seems complicated enough to have it's own module so we might just have an alias to color library

const ss = sx.stylesheet.create({....}) // just autoprefixer (for now)
ss.stringify() // json with key: inline styles as string  so you can use it anywere, even from php ^^
// could be stringified to key: styles or even to a json+css file (like a css modules)

// convenient ways
import {utils color, unit, stylesheet} from "notcss"
```

Not sure for a react helper yet.

**Comment by bloodyowl** [comment]
## server-side rendering

```javascript
React.renderToString(
  <ResizeProvider
    initialViewport={{ width: collectedWidth, height: collectedHeight }}
    getViewport={({ width, height }) => width > 1000 ? "L" : "M"}>
    {() => <App />}
  </ResizeProvider>,
  mountNode
)
```

**Comment by MoOx** [comment]
Good point.

**Comment by MoOx** [comment]
Hop https://github.com/bloodyowl/stile
